Develop
gtech-mulearn/Github-Enablment-Task pull request #689
Opened 2024-08-16 05:30 UTC by aryancholakkal

Created branch develop, feature
Added features
Final PR

2024-08-16 16:06 UTC, elementaryrock requested changes

2024-08-16 16:06 UTC, elementaryrock commented on Aryan_C_book_app/add_book_feature/list_all_books.txt
> +List all books will list all books in ascending order.
There should be two sentences here

2024-08-16 16:41 UTC, aryancholakkal commented
Done the changes requested

2024-08-17 06:36 UTC, elementaryrock requested changes

2024-08-17 06:36 UTC, elementaryrock commented on Aryan_C_book_app/add_book_feature/list_all_books.txt
> +List all books will list all books in ascending order.
Pls add in "This is the feature which shows the user all the books they've created as a list."

2024-08-17 06:36 UTC, elementaryrock commented on Aryan_C_book_app/add_book_feature/list_all_books.txt
> +This is a new feature.
Remove line 2 and 3

2024-08-17 07:17 UTC, merged