Develop
gtech-mulearn/Github-Enablment-Task pull request #815
Opened 2024-12-26 11:54 UTC by noobvp69

Added a new feature to list all books created by the user. 
The feature includes a description in `list_all_books.txt` explaining its functionality. 
Additionally, added a second line to describe the feature in more detail.

2024-12-26 15:34 UTC, elementaryrock requested changes

2024-12-26 15:34 UTC, elementaryrock commented on ayush_vp_book_app/add_books_feature/list_all_books.txt
> +List all books will list all books in ascending order.
Add in create_books.txt file

2024-12-26 15:46 UTC, noobvp69 reviewed
"The description for the 'list all books' feature has been added to create_books.txt. Changes have been pushed to the develop branch."

2024-12-30 13:30 UTC, elementaryrock requested changes

2024-12-30 13:30 UTC, elementaryrock commented on create_books.txt
> +This is the feature which shows the user all the books they’ve created as a list.
add this inside the folder

2025-01-04 16:34 UTC, closed without merging